# Usa a imagem oficial do nginx
FROM nginx:latest

# Label
LABEL maintainer="" version="" description=""

# Expõe as portas
EXPOSE 80 443 8080

# Comando para executar o nginx em primeiro plano
CMD ["nginx", "-g", "daemon off;"]