server {
    listen 80;
    listen [::]:80;

    server_name myproject.local;

    # Caminho absoluto até a pasta public do Laravel
    root /var/www/myproject/public;

    index index.php index.html;

    charset utf-8;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Desativa logs desnecessários
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    # Configuração de como o Nginx deve repassar o PHP para o PHP-FPM
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm:9000; # Usa o nome do serviço definido no docker-compose
        fastcgi_index index.php;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Bloqueia o acesso a arquivos ocultos (ex: .git)
    location ~ /\.(?!well-known).* {
        deny all;
    }
}